Repository tudo-aqua/bgw, pull requests merged in 2021-08, with the labels that each got.

#144 Readonly properties feature
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/DynamicComponentView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/container/CardStack.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/container/LinearLayout.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/CheckBox.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ColorPicker.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ComboBox.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/LabeledUIComponent.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ListView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ProgressBar.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextInputUIComponent.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ToggleButton.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/UIComponent.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/BoardGameApplication.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/BoardGameScene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/Scene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/BooleanProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/DoubleProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/IntegerProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/LimitedDoubleProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/Property.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/ReadonlyBooleanProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/ReadonlyDoubleProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/ReadonlyIntegerProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/ReadonlyProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/ReadonlyStringProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/properties/StringProperty.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/visual/ColorVisual.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/visual/ImageVisual.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/visual/SingleLayerVisual.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/visual/TextVisual.kt
  bgw-core/src/test/kotlin/observable/property/LimitedDoublePropertyTest.kt
  bgw-core/src/test/kotlin/observable/property/PropertyTestBase.kt
Labels: feature

#143 Scale animation feature
  bgw-core/src/main/kotlin/tools/aqua/bgw/animation/ScaleAnimation.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/AnimationBuilder.kt
Labels: feature

#142 Restrict opacity property setter feature
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
Labels: feature

#156 Fixed font color not being applied to TableView.
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
Labels: bug

#148 Nullable functions for stack feature
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Stack.kt
  bgw-core/src/test/kotlin/util/stack/PeekTest.kt
  bgw-core/src/test/kotlin/util/stack/PopTest.kt
  bgw-core/src/test/kotlin/util/stack/PushTest.kt
  bgw-core/src/test/kotlin/util/stack/SizeTest.kt
  bgw-core/src/test/kotlin/util/stack/SortShuffleTest.kt
  bgw-core/src/test/kotlin/util/stack/StackTestBase.kt
Labels: feature

#147 Scale not considered bug
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/DragDropHelper.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/DragTargetObject.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/container/GameComponentContainer.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/layoutviews/GridPane.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/layoutviews/Pane.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/Scene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Coordinate.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/CoordinatePlain.kt
Labels: bug

#158 Increase rerender performance
  bgw-core/detekt-rules.yml
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/ContainerNodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/LayoutNodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/PerformanceUtil.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/container/GameComponentContainer.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/container/LinearLayout.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/gamecomponentviews/DiceView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/layoutviews/Pane.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/Scene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/ObservableList.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/observable/ValueObservable.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/visual/CompoundVisual.kt
  bgw-core/src/test/kotlin/observable/observablelist/ObservableListTestBase.kt
  bgw-docs-examples/src/main/kotlin/examples/components/container/AreaExample.kt
  bgw-docs-examples/src/main/kotlin/examples/components/container/ContainerExample.kt
Labels: performance

#159 Auto grid size calculation bug
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/LayoutNodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/layoutviews/GridPane.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Coordinate.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/CoordinatePlain.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Trig.kt
  bgw-core/src/test/kotlin/util/coordinates/CoordinatePlainTest.kt
  bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/view/MauMauGameScene.kt
Labels: bug
