Repository tudo-aqua/bgw, pull requests merged in 2021-09, with the labels that each got.

#169 Update README.md
  README.md
Labels: documentation

#177 Fixed NullPointerException due to race condition in Frontend#sizeChanged
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
Labels: bug

#175 Fix recursive position search in containers for MovementAnimation#toComponentView
  bgw-core/src/main/kotlin/tools/aqua/bgw/animation/MovementAnimation.kt
Labels: unexpected behaviour

#178 Added missing docs for Stack
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
  docs/util/coordinate/coordinate.md
  docs/util/stack/stack.md
Labels: documentation

#179 Added missing documentation for readonly properties.
  docs/concepts/observable/observable.md
Labels: documentation

#180 Empty grid columns and rows get rendered size 0.0 even with fixed dimensions.
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/LayoutNodeBuilder.kt
Labels: unexpected behaviour

#184 BoardGameScene getting shown blurred if showGameScene gets called after hideMenuScene
  CHANGELOG.md
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
Labels: bug

#185 Removed all non-null assertions replacing them with safe calls or state checks.
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/AnimationBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/DialogBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/Scene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/dialog/Dialog.kt
Labels: performance

#189 Fixed wrong parent in rollback search for containers after drag and drop
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
Labels: bug

#190 Fix toComponentView animation missing layoutFromCenter offset for Grid.
  bgw-core/src/main/kotlin/tools/aqua/bgw/animation/MovementAnimation.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
Labels: bug

#191 Merge Dev for v0.4 deploy
  CHANGELOG.md
  bgw-core/src/main/kotlin/tools/aqua/bgw/animation/MovementAnimation.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/AnimationBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/DialogBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/FXConverters.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/LayoutNodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/layoutviews/GridPane.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextArea.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextField.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextInputUIComponent.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/core/Scene.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/dialog/Dialog.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/CoordinatePlain.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Stack.kt
  bgw-core/src/main/kotlin/tools/aqua/bgw/util/Trig.kt
  bgw-core/src/test/kotlin/util/coordinates/CoordinatePlainTest.kt
Labels: deploy
